actor Client

group Plaid account setup

Client -> API_Server: Account setup initiation
API_Server -> Plaid: Request Stripe token
Plaid -> API_Server: Get Stripe token
API_Server -> Stripe: Request Customer Object
Stripe -> API_Server: Get Customer Object
API_Server -> Client: Return OK

end

group Individual payment

SMS -> API_Server: Confirm tripler
API_Server -> Stripe: Initiate payment request
Stripe -> API_Server: Payment status update

end

group See payment log for user

Client -> API_Server: Request payments log
API_Server -> Stripe: Proxy transactions request
Stripe -> API_Server: Transactions log entries
API_Server -> Client: Response to payments log request

end
